@startuml Actors
skinparam dpi 300
left to right direction

' Human actors
actor "Network/Security\n  Administrator" as Admin
actor "IT Manager" as ITM

' Force same horizontal alignment
Admin -[hidden]-> ITM

@enduml