@startuml class1
skinparam dpi 300

Enum Role {
    ADMIN
    IT_MANAGER
    --

}

Enum Severity {
    LOW
    MEDIUM
    HIGH
    CRITICAL
    --

}

Enum Status {
    NEW
    ACKNOWLEDGED
    RESOLVED
    --

}

Enum Format {
    PDF
    --

}

Enum AttackCategory {
    BENIGN
    Bot
    DDoS
    DoS_GoldenEye
    DoS_Hulk
    DoS_Slowhttptest
    DoS_slowloris
    FTP-Patator
    Heartbleed
    Infiltration
    PortScan
    SSH-Patator
    Web_Attack
    --

}


' Core Classes 

class User {
    - id: Long
    - username: String
    - email: String
    - passwordHash: String
    - role: Role
    - createdAt: DateTime
    --

}

class Alert {
    - id: Long
    - severity: Severity
    - raisedAt: DateTime
    - acknowledgedAt: DateTime
    - resolvedAt: DateTime
    - analystNotes: String
    - status: Status
    --

}

class Attack {
    - id: Long
    - name: String
    - category: AttackCategory
    - defaultSeverity: Severity
    - description: String
    --

}

class NetworkFlow {
    - id : Long
    - timestamp: DateTime
    - sourceIP: String
    - destinationIP: String
    - sourcePort: int
    - destinationPort: int
    - protocol: String
    - fwdPackets: int
    - bwdPackets: int
    - fwdBytes: Long
    - bwdBytes: Long
    - flowDuration: float
    - flowBytesPerSec: float
    - flowPacketsPerSec: float
    - avgPacketSize: float
    - fwdPacketLengthMean: float
    - bwdPacketLengthMean: float
    - minPacketLength: int
    - synCount: int
    - ackCount: int
    - finCount: int
    - pshCount: int
    - urgCount: int
    - downUpRatio: float
    - initWinBytesForward: int
    - initWinBytesBackward: int
    - predictionLabel: String
    - confidence: float  
    --

}

class AuditLog {
    - id: Long
    - timestamp: DateTime
    - action: String
    - details: String
    --

}

class Report {
    - id: Long
    - title: String
    - generatedAt: DateTime
    - periodStart: DateTime
    - periodEnd: DateTime 
    - format: Format
    - filePath: String
    --

}

class Configuration {
    - id: Long
    - key: String
    - value: String
    - updatedAt: DateTime
    --

}

@enduml