@startuml class1
skinparam dpi 300

Enum Role {
    ADMIN
    IT_MANAGER
    --

}

Enum Severity {
    LOW
    MEDIUM
    HIGH
    CRITICAL
    --

}

Enum AlertStatus {
    NEW
    ACKNOWLEDGED
    RESOLVED
    DISMISSED
    --

}

Enum Format {
    PDF
    --

}

Enum AttackCategory {
    BENIGN
    Bot
    DDoS
    DoS_GoldenEye
    DoS_Hulk
    DoS_Slowhttptest
    DoS_slowloris
    FTP-Patator
    Heartbleed
    Infiltration
    PortScan
    SSH-Patator
    Web_Attack
    --

}


' Core Classes 

class User {
    - id: Long
    - username: String
    - email: String
    - passwordHash: String
    - role: Role
    - createdAt: DateTime
    --

}

class Alert {
    - id: Long
    - severity: Severity
    - raisedAt: DateTime
    - acknowledgedAt: DateTime
    - resolvedAt: DateTime
    - analystNotes: String
    - status: AlertStatus
    --

}

class Attack {
    - id: Long
    - name: String
    - category: AttackCategory
    - defaultSeverity: Severity
    - description: String
    --

}

class NetworkFlow {
    - id : Long
    - timestamp: DateTime
    - sourceIP: String
    - destinationIP: String
    - sourcePort: int
    - destinationPort: int
    - protocol: String
    - fwdPackets: int
    - bwdPackets: int
    - fwdBytes: Long
    - bwdBytes: Long
    - flowDuration: float
    - flowBytesPerSec: float
    - flowPacketsPerSec: float
    - avgPacketSize: float
    - fwdPacketLengthMean: float
    - bwdPacketLengthMean: float
    - minPacketLength: int
    - synCount: int
    - ackCount: int
    - finCount: int
    - pshCount: int
    - urgCount: int
    - downUpRatio: float
    - initWinBytesForward: int
    - initWinBytesBackward: int
    - predictionLabel: String
    - confidence: float  
    --

}

class AuditLog {
    - id: Long
    - timestamp: DateTime
    - action: String
    - details: String
    --

}

class Report {
    - id: Long
    - title: String
    - generatedAt: DateTime
    - periodStart: DateTime
    - periodEnd: DateTime 
    - format: Format
    - filePath: String
    --

}

class Configuration {
    - id: Long
    - key: String
    - value: String
    - updatedAt: DateTime
    --

}

' ─── Class Relationships ──────────────────────────────

' A flow triggers at most one alert
NetworkFlow "1"   -right-  "0..1"  Alert      : triggers 

' An alert is classified as one attack type
Alert          "0..*"   -right-  "1"     Attack : classified as 

' Admin manages alert status
User           "1"   --  "0..*"  Alert      : manages 

' User actions recorded in audit log
User           "1"   -right-  "0..*"  AuditLog   : generates

' Report aggregates alerts over a period
Report         "1"   --  "0..*"  Alert      : contains 


Report -[hidden]right- User
Attack -up- AttackCategory
Report -up- Format
Alert -down- AlertStatus
Alert -- Severity
User -up- Role
Attack -- Severity

AuditLog -[hidden]up- Configuration

@enduml