@startuml
autonumber
hide circle

skinparam sequenceParticipant underline
skinparam SequenceGroupBorderThickness 1.1


actor ":Network_Admin" as Admin
participant ":UI-Dashboard" as UI
participant ":C-Simulation" as Sim
participant ":AI-Engine" as AI
participant ":Configuration" as Config
participant ":NetworkFlow" as NF
participant ":Attack" as AttackE
participant ":Alert" as AlertE
participant ":Email_Service" as Email

Admin -> UI :: click_btn_Trigger_Network_Analysis()
activate Admin
activate UI
deactivate Admin
deactivate UI

UI -> Sim :: start_simulation()
activate UI
activate Sim
deactivate UI
deactivate Sim

Sim -> Config :: select(csv_path)
        activate Sim
        activate Config
        deactivate Sim
        deactivate Config

Sim -> Config :: select(delay)
        activate Sim
        activate Config
        deactivate Sim
        deactivate Config



autonumber stop
Sim -[#white]> 
autonumber resume
activate Sim
Sim -> Sim :: load_csv()
autonumber stop
Sim -[#white]> 
autonumber resume
deactivate Sim

alt CSV not found
    Sim -> UI :: error(CSV_NOT_FOUND)
    activate Sim
    activate UI
    deactivate Sim
    deactivate UI

    autonumber stop
    UI -[#white]> AlertE
    autonumber resume
    

else else

autonumber stop
UI -[#white]> AlertE
autonumber resume
autonumber stop
UI -[#white]> AlertE
autonumber resume
autonumber stop
UI -[#white]> AlertE
        autonumber resume
    loop 

        Sim -> AI :: predict(feature_vector)
        activate Sim
        activate AI
        deactivate Sim
        deactivate AI

        autonumber stop
        UI -[#white]> AlertE
        autonumber resume
        autonumber stop
        UI -[#white]> AlertE
        autonumber resume
        autonumber stop
        UI -[#white]> AlertE
        autonumber resume

        alt AI engine unavailable

            Sim -> UI :: error(AI_ENGINE_ERROR)
            activate Sim
            activate UI
            deactivate Sim
            deactivate UI

        else else

            AI --> Sim :: return_prediction()
            activate AI
            activate Sim
            deactivate AI
            deactivate Sim

            autonumber stop
            UI -[#white]> AlertE
            autonumber resume
            autonumber stop
            UI -[#white]> AlertE
            autonumber resume
            autonumber stop
            UI -[#white]> AlertE
            autonumber resume

            alt predictedLabel = BENIGN

                Sim -> NF :: insert(networkFlow fields)
                activate Sim
                activate NF
                deactivate Sim
                deactivate NF
                autonumber stop
                UI -[#white]> AlertE
                autonumber resume
                autonumber stop
                UI -[#white]> AlertE
                autonumber resume
                autonumber stop
                UI -[#white]> AlertE
                autonumber resume

            else predictedLabel = UNKNOWN

                Sim -> NF :: insert(networkFlow fields, diagnostics fields)
                activate Sim
                activate NF
                deactivate Sim
                deactivate NF
                autonumber stop
                UI -[#white]> AlertE
                autonumber resume
                autonumber stop
                UI -[#white]> AlertE
                autonumber resume
                autonumber stop
                UI -[#white]> AlertE
                autonumber resume

            else predictedLabel != BENIGN

                Sim -> NF :: insert(networkFlow fields)
                activate Sim
                activate NF
                deactivate Sim
                deactivate NF

                Sim -> AttackE :: select(severity)
                activate Sim
                activate AttackE
                deactivate Sim
                deactivate AttackE

                Sim -> AlertE :: insert()
                activate Sim
                activate AlertE
                deactivate Sim
                deactivate AlertE

                Sim -> UI :: display(alert)
                activate Sim
                activate UI
                deactivate Sim
                deactivate UI
                autonumber stop
                UI -[#white]> AlertE
                autonumber resume
                autonumber stop
                UI -[#white]> AlertE
                autonumber resume
                autonumber stop
                UI -[#white]> AlertE
                autonumber resume

                alt Severity = CRITICAL

                    Sim -> Email :: send_immediate_alert()
                    activate Sim
                    activate Email
                    deactivate Sim
                    deactivate Email

                else Severity = HIGH
                    autonumber stop
                    UI -[#white]> AlertE
                    autonumber resume
                    autonumber stop
                    UI -[#white]> AlertE
                    autonumber resume
                    autonumber stop
                    UI -[#white]> AlertE
                    autonumber resume

                  
                    autonumber stop
                    Sim -[#white]> NF
                    autonumber resume
                    activate Sim
                    Sim -> Sim :: start_unacknowledged_timer(5minute)
                    autonumber stop
                    Sim -[#white]> NF
                    autonumber resume
                    deactivate Sim

                    Sim -> AlertE :: select_unacknowledged_alert()
                    activate Sim
                    activate AlertE
                    deactivate Sim
                    deactivate AlertE

                    Sim -> Email :: send_unacknowledged_alert()
                    activate Sim
                    activate Email
                    deactivate Sim
                    deactivate Email

                    autonumber stop
                    UI -[#white]> NF
                    autonumber resume
                    autonumber stop
                    Sim -[#white]> AttackE

                   autonumber resume
                   autonumber stop
                   Sim -[#white]> AttackE

                end

                autonumber resume
                autonumber stop
                Admin -[#white]> AttackE

                autonumber resume
                autonumber stop
                Admin -[#white]> AttackE

            end
            

            autonumber stop
            Admin -[#white]> AttackE
        
           autonumber stop
           UI -[#white]> AlertE
           autonumber resume
           autonumber stop
        

        end
       

        autonumber stop
        Sim -[#white]> AlertE
        autonumber resume
        activate Sim
        Sim -> Sim :: delay(configurable_ms)
        autonumber stop
        Sim -[#white]> AlertE
        autonumber resume
        deactivate Sim       
        autonumber stop
        Admin -[#white]> AlertE


    end

    autonumber resume
    autonumber stop
    UI -[#white]> AlertE
    autonumber resume
    autonumber stop
    UI -[#white]> AlertE
    autonumber resume
    autonumber stop
    UI -[#white]> AlertE
    autonumber resume

    Sim -> UI :: simulation_complete()
    activate Sim
    activate UI
    deactivate Sim
    deactivate UI

autonumber stop
Admin -[#white]> UI
end
@enduml