@startuml use-Case
skinparam dpi 300
left to right direction
skinparam packageStyle rectangle


' ─── Left Actors ──────────────────────────────────────
actor "User" as User
actor "Network/Security\nAdministrator" as Admin
actor "IT Manager"                       as ITMgr


' ─── System Boundary ──────────────────────────────────
rectangle "NIDS Web Application" {

    usecase "Trigger Network Analysis" as UC_NET
    usecase "Analyze Network Flow" as UC_NET_FLOW
    usecase "send Alert" as UC_ALERT

    usecase "Authenticate" as UC_AUTH


    usecase "View Dashboard"          as UC_VIEW_DASH
    usecase "View Statistics Summary" as UC_VIEW_STATS


    usecase "View Alerts List"  as UC_ALERT_LIST
    usecase "View Alert Detail" as UC_ALERT_DETAIL
    usecase "Search Alerts" as UC_ALERT_SEARCH
    usecase  "Manage Alert Status" as UC_ALERT_STATUS

    usecase "View Reports"  as UC_VIEW_REPORTS
    usecase "Export Report" as UC_EXPORT_REPORT
    usecase "Generate Report" as UC_GEN_REPORT
    usecase "View Report" as UC_VIEW_REPORT
    usecase "View \nDetail" as UC_VIEW_REPORT_DETAIL
    usecase "view" as v
    usecase "view" as v2

}

' ─── Right Actor ──────────────────────────────────────
rectangle "     <<actor>>\n\nEmail Service\n" as DE

UC_AUTH       -[hidden]left- UC_VIEW_DASH
UC_VIEW_DASH  -[hidden]left- UC_VIEW_STATS
UC_VIEW_STATS -[hidden]left- UC_NET


UC_ALERT_LIST -[hidden]left- UC_VIEW_REPORT_DETAIL
UC_ALERT_LIST -[hidden]right- v

' ─── Admin + IT Manager associations ───────────────────────────────
User -[hidden]- UC_AUTH
User -[hidden]- UC_VIEW_DASH
User -[hidden]- UC_VIEW_STATS

' ─── Admin associations ───────────────────────────────
Admin -[hidden]- UC_NET
Admin -[hidden]- UC_ALERT_LIST



' ─── IT Manager associations ──────────────────────────
ITMgr -[hidden]- UC_VIEW_REPORTS




' ─── Email Service associations ───────────────────
UC_ALERT -down- DE 


UC_NET .down.> UC_NET_FLOW : <<include>>
UC_ALERT .left.> UC_NET_FLOW : <<extend>>



UC_ALERT_SEARCH .up.> UC_ALERT_LIST : <<extend>>
UC_ALERT_DETAIL .up.> UC_ALERT_LIST : <<extend>>

UC_NET -[hidden]down- UC_ALERT

UC_ALERT_STATUS .right.> UC_ALERT_DETAIL : <<extend>>

UC_EXPORT_REPORT .up.> UC_VIEW_REPORTS : <<extend>>
UC_GEN_REPORT .up.> UC_VIEW_REPORTS : <<extend>>

UC_EXPORT_REPORT .[hidden]left.> UC_GEN_REPORT 

UC_VIEW_REPORTS -[hidden]right- UC_VIEW_REPORT_DETAIL



@enduml

' ─── Relationships ────────────────────────────────────
'UC_EXPORT_REPORT .right.> UC_VIEW_DASH : <<extend>>
'UC_AUTH .down.> UC_VIEW_DASH : <<include>>

'UC_EXPORT_REPORT .up.> UC_VIEW_DASH : <<extend>>
'UC_EXPORT_REPORT .right.> UC_VIEW_DASH : <<extend>>

'UC_ALERT_STATUS .up.> UC_ALERT_LIST : <<extend>>